### ISSUE TITLE
Issue with original broadlink switch

### ISSUE THREAD

**Issue by gianpyc** [vpnmaster/homeassistant-custom-components#41]
Thanks very much for this fantastic custom comment. However, once added this I have an issue with the normal broadlink switch module. In fact, when starting home assistant I get:
```
ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform broadlink
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 82, in async_setup
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/switch/broadlink.py", line 145, in setup_platform
    broadlink_device = broadlink.rm((ip_addr, 80), mac_addr)
TypeError: __init__() missing 1 required positional argument: 'devtype'
```

Is there any way to fix this issue?

Thanks

**Comment by vpnmaster** [comment]
It seems to me that you are not using the last HA version. Is that the case?

**Comment by gianpyc** [comment]
Using this HA version:
0.65.6

Should I update it?
Thanks

**Comment by vpnmaster** [comment]
Yes. Switch in 0.65.6 uses an older version of broadlink library.

**Comment by gianpyc** [comment]
Ok, thanks I try
