### ISSUE TITLE
missing 1 required positional argument: 'devtype'

### ISSUE THREAD

**Issue by MACscr** [vpnmaster/homeassistant-custom-components#83]
Getting this error in my home-assistant.log:

`2018-09-19 05:09:42 WARNING (MainThread) [homeassistant.loader] You are using a custom component for fan.broadlink which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2018-09-19 05:09:44 ERROR (MainThread) [homeassistant.components.fan] Error while setting up platform broadlink
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fan/broadlink.py", line 71, in setup_platform
    broadlink_device = broadlink.rm((ip_addr, 80), mac_addr)
TypeError: __init__() missing 1 required positional argument: 'devtype'`

my fans.yaml has the following:

`platform: broadlink
host: 192.168.1.211
mac: '34:ea:34:89:19:23'
name: Bedroom Fan
rfcodes_ini: 'broadlink_fan_codes/bedroom_fan.ini'
default_speed: low
defaut_direction: left
customize:
    speeds:
        - low
        - medium
        - high`

**Comment by MACscr** [comment]
Is there a reason why this was closed without any response?
