### ISSUE TITLE
Breaks in 0.84. 

### ISSUE THREAD

**Issue by tyjtyj** [vpnmaster/homeassistant-custom-components#93]
This custom component break in 0.84

```
2018-12-12 23:28:42 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate.broadlink. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 92, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/climate/broadlink.py", line 14, in <module>
    from homeassistant.helpers.restore_state import async_get_last_state

```

**Comment by tyjtyj** [comment]
already fix it seems
